### ISSUE TITLE
Getting import errors

### ISSUE THREAD

**Issue by contentmaverick** [synapsepay/SynapsePayRest-Python#15]
Hi,

This line of code 
`from synapse_pay_rest import Client` 
causes 
`ImportError: No module named 'synapse_pay_rest.api.users'`

The reason was because this file **SynapsePayRest-Python/synapse_pay_rest/api/__init__.py** has the following code:

`from .users import Users`
`from .nodes import Nodes`
`from .trans import Trans`

but the files in **SynapsePayRest-Python/synapse_pay_rest/api/** folders are named Users.py and Nodes.py. If you renamed Users.py to users.py and Nodes.py to nodes.py then the import error doesn't happen.

Please let me know when this is fixed.

Thanks

Paras

**Comment by stevula** [comment]
git was not recognizing the case change in the file names but it should be fixed now in version 1.1.1.
