### ISSUE TITLE
implement transaction idempotency keys

### ISSUE THREAD

**Issue by stevula** [synapsepay/SynapsePayRest-Python#20]

**Comment by prsauer** [comment]
Is this being worked on?

**Comment by stevula** [comment]
Yes, we will be working on this and some other updates over the next few days.

**Comment by stevula** [comment]
@teganduong you can refer here in the ruby library, though I think we might need to rewrite part of the client (the headers):

https://github.com/synapsepay/SynapsePayRest-Ruby/pull/53/files
